version: '3.8'

services:
  fastapi:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    ports:
      - "8504:8504"
    volumes:
      - ./FastAPI:/app
    environment:
      - DATABASE_URL=test.db

  streamlit:
    build:
      context: ./Streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
